"""Phase 0 foundation stack.

Contains only what Phase 0 calls for:

* an account-level AWS Budget so nothing can run away silently
* the DynamoDB single table that every later phase writes to
* one Secrets Manager entry holding all third-party credentials

Everything else -- API Gateway, Lambdas, Step Functions, S3, SES, ECS -- lands
in later phases.

Single-table access patterns (documented here so the shape stays deliberate):

    PLAYER#<player_id>   PROFILE                the player record
    PLAYER#<player_id>   EVENT#<ts>#<id>        timeline: every in/outbound event
    PLAYER#<player_id>   BEAT#<beat_id>         per-beat state and outcome
    PLAYER#<player_id>   QUOTA#<yyyy-mm-dd>     daily send counters (ttl'd)
    CHAT#<channel>#<id>  PLAYER                 inbound channel -> player lookup

    GSI1: gsi1pk = STATUS#<status>, gsi1sk = <last_contact_iso>
          -> the admin panel player list, ordered by staleness
"""

from __future__ import annotations

import json

from aws_cdk import CfnOutput, RemovalPolicy, Stack, Tags
from aws_cdk import aws_budgets as budgets
from aws_cdk import aws_dynamodb as dynamodb
from aws_cdk import aws_secretsmanager as secretsmanager
from constructs import Construct

from infra.config import PROJECT, EnvConfig, budget_alert_email

# Placeholder keys created with the secret. Values are filled in out-of-band
# (console or CLI) and are never regenerated by a later deploy.
SECRET_TEMPLATE_KEYS = {
    "telegram_bot_token": "",
    "twilio_account_sid": "",
    "twilio_auth_token": "",
    "twilio_phone_number": "",
    "ses_from_address": "",
}


class AdventureAgentStack(Stack):
    def __init__(
        self, scope: Construct, construct_id: str, *, cfg: EnvConfig, **kwargs
    ) -> None:
        super().__init__(
            scope,
            construct_id,
            stack_name=cfg.stack_name,
            termination_protection=cfg.termination_protection,
            description=f"Personal AI Adventure Agent -- {cfg.name} foundation",
            **kwargs,
        )
        self.cfg = cfg

        Tags.of(self).add("project", PROJECT)
        Tags.of(self).add("env", cfg.name)

        self.removal_policy = (
            RemovalPolicy.RETAIN if cfg.retain_data else RemovalPolicy.DESTROY
        )

        if cfg.creates_budget:
            self.budget = self._make_budget()
        self.table = self._make_table()
        self.secret = self._make_secret()

        self._outputs()

    # ---------------------------------------------------------------- budget

    def _make_budget(self) -> budgets.CfnBudget:
        """Account-wide monthly cost budget.

        Not filtered by tag: tag-scoped budgets require the cost-allocation tag
        to be activated in the Billing console and take ~24h to start
        collecting, which would leave the first day of spend unguarded.
        Account-wide alerts earlier, which is the safer failure mode.
        """
        email = budget_alert_email()

        def notify(threshold: float, forecast: bool = False):
            return budgets.CfnBudget.NotificationWithSubscribersProperty(
                notification=budgets.CfnBudget.NotificationProperty(
                    comparison_operator="GREATER_THAN",
                    notification_type="FORECASTED" if forecast else "ACTUAL",
                    threshold=threshold,
                    threshold_type="PERCENTAGE",
                ),
                subscribers=[
                    budgets.CfnBudget.SubscriberProperty(
                        address=email, subscription_type="EMAIL"
                    )
                ],
            )

        return budgets.CfnBudget(
            self,
            "MonthlyBudget",
            budget=budgets.CfnBudget.BudgetDataProperty(
                budget_name=f"{PROJECT}-monthly",
                budget_type="COST",
                time_unit="MONTHLY",
                budget_limit=budgets.CfnBudget.SpendProperty(
                    amount=self.cfg.monthly_budget_usd, unit="USD"
                ),
            ),
            notifications_with_subscribers=[
                notify(50.0),
                notify(80.0),
                notify(100.0),
                notify(100.0, forecast=True),
            ],
        )

    # ----------------------------------------------------------------- state

    def _make_table(self) -> dynamodb.TableV2:
        """The single table. On-demand billing -- 10 players is nothing."""
        return dynamodb.TableV2(
            self,
            "Table",
            table_name=self.cfg.prefix,
            partition_key=dynamodb.Attribute(
                name="pk", type=dynamodb.AttributeType.STRING
            ),
            sort_key=dynamodb.Attribute(name="sk", type=dynamodb.AttributeType.STRING),
            billing=dynamodb.Billing.on_demand(),
            time_to_live_attribute="ttl",
            global_secondary_indexes=[
                dynamodb.GlobalSecondaryIndexPropsV2(
                    index_name="gsi1",
                    partition_key=dynamodb.Attribute(
                        name="gsi1pk", type=dynamodb.AttributeType.STRING
                    ),
                    sort_key=dynamodb.Attribute(
                        name="gsi1sk", type=dynamodb.AttributeType.STRING
                    ),
                    projection_type=dynamodb.ProjectionType.ALL,
                )
            ],
            point_in_time_recovery_specification=dynamodb.PointInTimeRecoverySpecification(
                point_in_time_recovery_enabled=self.cfg.point_in_time_recovery
            ),
            # AWS-owned key: no KMS charge. Nothing here is regulated data.
            encryption=dynamodb.TableEncryptionV2.dynamo_owned_key(),
            deletion_protection=self.cfg.retain_data,
            removal_policy=self.removal_policy,
        )

    # --------------------------------------------------------------- secrets

    def _make_secret(self) -> secretsmanager.Secret:
        """One JSON secret per environment holding every third-party credential.

        One entry rather than five: Secrets Manager bills $0.40 per secret per
        month, and at this scale a single JSON blob is simpler to rotate by
        hand. ``telegram_webhook_secret`` is generated here so it never has to
        be invented or typed by a human. Generated values are produced once, at
        create time -- a later deploy will not overwrite hand-entered values.
        """
        return secretsmanager.Secret(
            self,
            "Credentials",
            secret_name=self.cfg.secret_name,
            description=(
                "Third-party credentials for the Adventure Agent "
                f"({self.cfg.name}). Fill the empty keys in by hand."
            ),
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template=json.dumps(SECRET_TEMPLATE_KEYS),
                # Telegram's secret_token allows [A-Za-z0-9_-] only.
                generate_string_key="telegram_webhook_secret",
                exclude_punctuation=True,
                include_space=False,
                password_length=48,
            ),
            removal_policy=self.removal_policy,
        )

    # --------------------------------------------------------------- outputs

    def _outputs(self) -> None:
        CfnOutput(self, "TableName", value=self.table.table_name)
        CfnOutput(self, "TableArn", value=self.table.table_arn)
        CfnOutput(self, "SecretName", value=self.cfg.secret_name)
        CfnOutput(self, "SecretArn", value=self.secret.secret_arn)
