#!/usr/bin/env python
"""Register (or inspect) the Telegram webhook.

    python scripts/telegram_setup.py whoami
    python scripts/telegram_setup.py set --url https://xxxx.execute-api.us-east-1.amazonaws.com/telegram/webhook
    python scripts/telegram_setup.py info
    python scripts/telegram_setup.py unset

The webhook secret is generated by Secrets Manager and read from there -- it is
never typed, printed, or stored anywhere else. ``set`` looks the API URL up
from the deployed stack outputs when ``--url`` is omitted.
"""

from __future__ import annotations

import argparse
import sys

from _common import add_env_argument, bootstrap


def _stack_webhook_url(env_name: str) -> str | None:
    import boto3

    stack = f"AdventureAgent{'Prod' if env_name == 'prod' else 'Dev'}"
    cfn = boto3.client("cloudformation")
    try:
        outputs = cfn.describe_stacks(StackName=stack)["Stacks"][0].get("Outputs", [])
    except Exception as exc:
        print(f"could not read stack {stack}: {exc}", file=sys.stderr)
        return None
    for output in outputs:
        if output["OutputKey"] == "TelegramWebhookUrl":
            return output["OutputValue"]
    return None


def _client():
    from backend.channels.telegram import TelegramClient
    from backend.core import secrets

    return TelegramClient(secrets.telegram_bot_token())


def cmd_whoami(_args) -> int:
    me = _client().get_me()
    print(f"@{me['username']}  ({me.get('first_name')}, id {me['id']})")
    return 0


def cmd_set(args) -> int:
    from backend.core import secrets

    url = args.url or _stack_webhook_url(args.env)
    if not url:
        print("no --url given and no TelegramWebhookUrl output found", file=sys.stderr)
        return 1

    _client().set_webhook(url, secret_token=secrets.telegram_webhook_secret())
    print(f"webhook set -> {url}")
    print("secret token taken from Secrets Manager (not shown)")
    return 0


def cmd_info(_args) -> int:
    info = _client().get_webhook_info()
    print(f"url                    {info.get('url') or '(none)'}")
    print(f"pending updates        {info.get('pending_update_count', 0)}")
    print(f"custom certificate     {info.get('has_custom_certificate')}")
    print(f"max connections        {info.get('max_connections')}")
    print(f"secret token set       {'secret_token' in info or bool(info.get('url'))}")
    if info.get("last_error_message"):
        print(f"LAST ERROR             {info['last_error_message']}")
        print(f"  at                   {info.get('last_error_date')}")
    return 0


def cmd_unset(_args) -> int:
    _client().delete_webhook()
    print("webhook removed")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    add_env_argument(parser)
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("whoami", help="confirm the bot token works").set_defaults(
        func=cmd_whoami
    )

    setter = sub.add_parser("set", help="point the bot at this environment's webhook")
    setter.add_argument("--url", default=None, help="defaults to the stack output")
    setter.set_defaults(func=cmd_set)

    sub.add_parser("info", help="show Telegram's view of the webhook").set_defaults(
        func=cmd_info
    )
    sub.add_parser("unset", help="remove the webhook").set_defaults(func=cmd_unset)
    return parser


def main() -> int:
    args = build_parser().parse_args()
    env = bootstrap(args.env)
    print(f"[{env}]")
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
